name: Greet and Label on Issue Creation

on:
  issues:
    types: [opened]

jobs:
  greet-and-label:
    runs-on: ubuntu-latest

    steps:
      - name: Greet User
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issue = context.payload.issue;
            const issueCreator = issue.user.login;
            const issueNumber = issue.number;
            const repo = context.payload.repository.full_name;

            const greetingMessage = `Hello @${issueCreator}! Thanks for creating issue #${issueNumber} on #${repo}.Please Comment /assign-me to self assign this issue to yourself, and please don't forget to star this repo.`;

            github.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issueNumber,
              body: greetingMessage
            });

      - name: Auto Label Issue
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const labelsToAdd = ['gssoc']; // Add your desired labels here
            const issueNumber = context.payload.issue.number;

            labelsToAdd.forEach(label => {
              github.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issueNumber,
                labels: [label]
              });
            });
