name: Comment and Label on Issue Opened
on:
  issues:
    types:
      - opened

jobs:
  comment_and_label:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Add comment
        uses: actions/github-script@v4
        with:
          script: |
            const commentAuthor = context.payload.issue.user.login;
            const commentBody = `Hey @${commentAuthor} ! \n Thank you for raising an issue üíó \n You can self assign the issue by commenting /assign in comment üòÄ \n Make sure you follow [CODE OF CONDUCT](https://github.com/Indie-Kart/ecommerce-store/blob/main/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/Indie-Kart/ecommerce-store/blob/main/Contributing.md) üöÄ \n Don‚Äôt Forget to ‚≠ê our [IndieKart](https://github.com/Indie-Kart/ecommerce-store/) `;
            const { owner, repo, number } = context.issue;

            await github.issues.createComment({
              owner: owner,
              repo: repo,
              issue_number: number,
              body: commentBody
            });

      - name: Add label if issue body contains "GSSoC24"
        id: check_label
        run: |
          if [[ $(echo "${{ github.event.issue.body }}" | grep -q "GSSoC24"; echo $?) == 0 ]]; then
            echo "::set-output name=add_label::true"
          else
            echo "::set-output name=add_label::false"
          fi

      - name: Add label "GSSoC23"
        if: ${{ steps.check_label.outputs.add_label == 'true' }}
        uses: actions/github-script@v4
        with:
          
          script: |
            const { owner, repo, number } = context.issue;

            await github.issues.addLabels({
              owner: owner,
              repo: repo,
              issue_number: number,
              labels: ["gssoc"]
            });
